# Generated by Django 6.0 on 2025-12-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='project_images/')),
            ],
        ),
    ]
